### ISSUE TITLE
[BUG] Example_addon needs update

### ISSUE THREAD

**Issue by 7ychu5** [Ansimist/cs2typescript#2]
line 1 
    `import { Instance } from "domains/serverpointentity"`
    -->
    `import { Instance } from "serverpointentity"`
    //import package location changed

line 65
    `Instance.PublicMethod("PlayerPawnTest",/*number*/ (num=0) => {`
    -->
    `Instance.PublicMethod("PlayerPawnTest",/*none*/ () => {`
    //pass the invaild args in Hammer IO will crash

misc
    `Instance.Log` --> `Instance.Msg`

**Comment by Ansimist** [comment]
Thank you. I've updated the addon example
